---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCSLDJUEOqOp4uLYll9+t/cHPGMMv3LRGLqxIPgjmWQh+Ph1/XAPXzgBdpaCuQ3Xy7vRlHvZlP4cwcDxeXLtPOJYqb0R4TEbIuFmRDmNw5CuHoToY9MlOTXOoBaud77iFme5di37rQH9wmA9NgrJelJb2VPeBAYtvuQUJIaQPtEnlHNn99f121QAkKANOHIRpNe15PuaZcCoH5QNSb+nxg7zULO0KO9M+J5iGCxb1g1z9livnAOznDZcoy6L2Dlx1jzxzZznGfuzQWcbaFYOY7rdffjVEgawNR5TUYLOGqqHp+mhCarSVXF0Nd4+Gn7mEpwNPFJcNMVhiDjx/09MyjaBARggEWHjwgR9fK4huyL+ikzYzSt5gMi11wyNeZNz8DbQ3cOaPSmmdFUKnIHXOkvn6dVF+pwA0G07XdZamCgck8DGvZG9hP/3PlGShDX1gTOFWon3LWLXfbRebtsokMwlr/Qb7sQwRQbny+mMGXY/uVV8+ZWfAiGe5rL8Frt5AO4YZCzCN2a93duuJStQI2Nb3cL9nYPwbYyBMS5RA8lfg41xQPGScURm/nWylUQ8+Pbtu72ZodQo7jNFLK1UZxKCAg6HyJNy4mml1EtG9tJnEpoiK9skSUqs8YTCudkrnh2IHHhfcZNcA5QWu381gC3Il6VFVDKPuajlzujycIKGG0/jLgdYXzxTcf87OP71uqEFfkp9Si10C4Q9uE9/YhRo6WwzA==
    admin-user: AgB/63cu+4QvtxSA+73Dwkiqb3ssPP8MDQDdTdepYin3ffHOCZKxvV25GcYJOnQIc4pwluApep0lblp7EmSxe2VNNSyEt0tuEgFuIzBKw8HDV2WsimJAQYS6hn1UNLlkQVvAQ8ZV9ESkIcCsknecHz5XGAtJxqgd79JUbGC+UrJ2WhXHydWQyB+2aov9nlJh9wZCF7rgAFZng2rl3AKBfqb/l6yLLPsxqx/dKsqOskUabfyESWkDxHBS02e2QdcHY/+8Ju/OoOO0o4Hcdd4goWTFO8jxsSf73D2Bou8RoFge+zNYZOEvlKeZiswS9eLdzGEkyExkN9hOhjUkuc1RxHt6cZw0MO2Nt0lh1krRu+XWxhxIMzOSLG9mCa/FZTeWYqO67dPb4xvHxfTDkhss/nVKAXycFkQGvPMZJYPzsJwvkMquLcC7iopbJLvNB8iID/aZNTJiI+JbddGVVYFBbKX3N8H6Uv/owwGETcc0yOz2DeXTFR5j47ciHIf9LnNEQv61AqiEy7S+IJcxQWhMeBOAEezDrvtcmHKEyOSvabiLjnzlUuxvDa4KIx5n7k1D0PjxiK9KLLlPMvSPxmdCXkbzyMw0siqykMrmx/3bNTAOV6sJPbse7H4jhm7BWMyx/bgK7zCkYtw4nSwG+XtOYJAPYMjo7ahywGPW4Qz6nw8VsO0/U+sGR/biMwnLjxdpvK1ag+jvuQ==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: Opaque
