---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAi+9sjN12bnwIP/emdxmKfgrRtDoecUYFMqjmb1yyk6p+rO2tRX0wbfR1te/V9QJo733Ih4bGNbPQinexrJqHSCaZixBzQPF5WSd123kOi1HLuBdWoSKmhi1i/vKB3ZwCgBtrzq6h+xIFGX4WXdUVmJcpo+REsQcpZVSoejSgQ1HHCzhfWf5QAOxhUhMJF5eKZGOkDbPdhRcVwMgLBsMSW2DcPh7qh5JbSgYLcsS9Qj24DylAjcL5FznhXkJwjYHjBZUJbL/O3mjUYuaj9WTbJ1MdCcQ6jRLFal4iE3Bz1xpp/omLjt2PqMFtUycqSXH1R6IDrklxj3qv5+pgAElSe3faDNegzCEMrIJxsUQPdhejYRBn+MLHhZwUSilTSB9NMQSB85QoM4yyqRA/NYmWHvKr1Mkj+lEsEzQy5UPsGLUxxijEIE0hwoZcYES+aBnkQ8TuT2DLL94EXvaAlcE+2e6zi1Y9zzlwMPacsJ+Yh3pRhiWK768QfiJlsZRb5iEtnPHjLyPppaEZY+0RVXAXWGNYlwJb87CazKyIeN5CfPDDzyPRB4pMKT/phSRlwFQABCMVMM3OYqhK2qYpLZtufKqVJEbjUjif1LZdGPd8F1fKI4wDYlCOje7wcG/g/uKifUvwcrHGO2KCkW3VhH7ThVye7k+zWTQr9e6oPbbKFh42hrCdXonCI2dao/SBv9tOSdjqKgNwXtKnecz4AMeAQeRLF1w==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: Opaque
