---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgB7FfZHh2XSORVs4Ot7jRvPud1FXlV+dKnIoQ/T0WBwBSHlf80RaTdfqTfKTN9PoL/JlrvNSAtQKYW1WEemSU4uLeHhzVKE3V5lREp8RiO8BmSpxJtqpzN8yW8bSXcVl8a8n0wV/TIlHaon/uYLA3ITLrfQd1RoNKJ5DhNiX0sLWcb28M/SZC0cBgkrCclHMnrXXEQZFYlxWQD8svgksGcDZ6tvn9lpDNMt9ZdaSKlIvF181Cs837HWNOT/guUz90zSimA5y/2EN3JcIfPx0fOoZHf6t4S6ka6hP88XrMRm9Fobf50WwbXK16bGA/Ko/+NzU5uyvi2nAV+WNh2XdD8R3mvsgLNytR+J+0pC6CbJgdq6AVnSGKkL9853EKoXCPLqF56iwRSjXTcUcc3XYVbCU57DFWLzIq1JjWzXtQ9i/TsmtEqhIVdJbYlE5AjSB4+QcnJSIsjx/BTSWARF3B/4VyA/x1i2eVv92TP3md1Zt+d1ehAQwhUtWaTQex9juxi8qx/gX2WrAsq+eXRkFms11s1XU+ZDRT8w8jNJo13xFLUrjxnbqQfM4Dh2B5L0jWeNv4zpuLuqDgZOhA9GOOVQbf/sfDvgGcVu6E5MWpQG0X5++zzmTMy26tb4lGlpFA3daYprh2WHPP6F36t3uTN7Ej9TZmxq3OdMuB8OOKvDgHrWgbTXFqVzsv9QiVmoffHI6ZmiltdgKYRpD3vi92OGzSy7rIZaWdQ=
    admin-user: AgCMvCoLlLmsUmiq7rOnvVYEz7otD4/JFDmogTOjERLI9PE1d1B1gns7GVIPUXeB8qkw8hX9OQmAvIL9iES/2QA7EYmNokd2KOp2itS/TsUiKjLfMbYpzI0vAz0/pMfNeFbd3cVwTHQZ2FsIMO8Fc+IyQKLVpY0zk4VpeoSkSY5oopR4bDXLTMMLcn1cGF3vF/bY3m9O0O4Thh9tAYJy7fXVs4El5wNlzi4WJN82qCGZCr6Xy7LwWNo/+Dx9qoI5vwpctPbwwYopxMjLblrWC+4PGKTfwNrLbURVvvyZJsdaqv+00269Dfemli3AQWOCwOiE8kz57TRK1LviXe69NwYSzUcreZVVbJoxmHswAyxYRu1uYnkuc8bNYFhrddg128DFLoysmNmK0Roz9oQHmkpD6S1peKCfna2o0kArSjTjXoiG/8RSi4xonMrM5kgsJGDHhi7AOxhWKdhreYhcmAg6M9r3akoBaFy6t/k2v7o0FU7SHly1rMR+Sv8i2kMmBVOIKeerU5WATGa7eQpM0IvGDHM4AOtJwsZTE5v4Huf+BcEQK3vlk3x59wdIWOXq/3dF94+Y1tPjSyIGqvvIzaQ4Ud233qR6NtPASB6paXYs73IXmHQbuuPuY3hvmVifeQ4sHMfXCC/UkFUKG2AFd/CJSsmJR0M1fP8t8QPY+ZuL7rZ/qGdG37cNFW9ozYD8NlIi0TgJmg==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
